const { Products } = require('../models');

const productdata = [
  {
    title: 'Lawn Mower',
    description: 'Honda 5.5hp 21 inch lawn mower',
    price: '$150',
    main_image: 'https://i.imgur.com/aVcs8kK.jpg',
    second_image: '',
    third_image: '',
    zipcode: '84020',
    user_id: '1',
     },
  {
    title: 'Mac Book Air',
    description: 'M1 Chip, 8-core CPU',
    price: '$750',
    main_image: 'https://i.imgur.com/fhMyf3W.jpg',
    second_image: 'https://i.imgur.com/XqGmahW.jpg',
    third_image: '',
    zipcode: '84108',
    user_id: '2'
     },
  {
    title: 'Winter Boots',
    description: 'Uggs size 7 Womens',
    price: '$50',
    main_image: 'https://i.imgur.com/drlVR1s.jpg',
    second_image: '',
    third_image: '',
    zipcode: '84120',
    user_id: '3'
     },
  {
    title: 'Snow Blower',
    description: 'Ariens Snow Thrower',
    price: '$550',
    main_image: 'https://i.imgur.com/TUGaeLh.jpg',
    second_image: 'https://i.imgur.com/xiXyTOV.jpg',
    third_image: '',
    zipcode: '84020',
    user_id: '2'
     },
  {
    title: 'Dyson V8 Vaccuum',
    description: 'handheld, lightweight, ergonomic cordless vaccuum',
    price: '450',
    main_image: 'https://i.imgur.com/Cs1dvB1.png',
    second_image: 'https://i.imgur.com/zW0H1J6.jpg',
    third_image: '',
    zipcode: '84120',
    user_id: '4',
    },
  {
    title: 'Lawn Mower',
    description: 'Troy Bilt 5hp 20inch lawn mower',
    price: '$475',
    main_image: 'https://i.imgur.com/JMQIrKp.jpg',
    second_image: 'https://i.imgur.com/9rJfzyj.jpg',
    third_image: '',
    zipcode: '84108',
    user_id: '5',
    },
  {
    title: 'Baby Stroller',
    description: 'City Mini GT2 Stroller',
    price: '$120',
    main_image: 'xxxx.jpg',
    second_image: 'https://i.imgur.com/7ZUoWyJ.jpg',
    third_image: '',
    zipcode: '84108',
    user_id: '5',
    },
  {
    title: 'Mountain Bike',
    description: 'Specialized Stumpjumper S-Works',
    price: '$6500',
    main_image: 'https://i.imgur.com/dxtxbCb.jpg',
    second_image: 'https://i.imgur.com/EmDmcKp.jpg',
    third_image: 'https://i.imgur.com/s1xv4Mn.jpg',
    zipcode: '84120',
    user_id: '6',
    },

  {
    title: 'Electric Lawn Mower',
    description: 'E-Go 20 inch lawn mower',
    price: '$699',
    main_image: 'xxxx.jpg',
    second_image: 'https://i.imgur.com/HYnRTcS.jpg',
    third_image: 'https://i.imgur.com/I0pz9Lc.jpg',
    zipcode: '84020',
    user_id: '7',
     },
  {
    title: '2010 Honda Accord',
    description: 'V6 Sport fuel efficient, great daily driver',
    price: '$8650',
    main_image: 'https://i.imgur.com/bPMT916.jpg',
    second_image: 'https://i.imgur.com/YT1Fivo.jpg',
    third_image: '',
    zipcode: '84108',
    user_id: '8',
      },
  {
    title: 'Apple iPhone 14',
    description: 'iPhone 14 Pro Max. Unlocked',
    price: '$1200',
    main_image: 'https://i.imgur.com/VWoAW6c.jpg',
    second_image: 'https://i.imgur.com/6Ayu75P.jpg',
    third_image: '',
    zipcode: '84120',
    user_id: '9',
      },
  {
    title: 'Scooter',
    description: 'Razor kids scooter',
    price: '$80',
    main_image: 'https://i.imgur.com/C0ZzF2d.jpg',
    second_image: '',
    third_image: '',
    zipcode: '84020',
    user_id: '10',
      },
  {
    title: 'YETI Rotomold Cooler 50qt',
    description: '7 day Ice Retention',
    price: '$400',
    main_image: 'https://i.imgur.com/Nz2QLZ1.jpg',
    second_image: '',
    third_image: '',
    zipcode: '84120',
    user_id: '11',
      },
  {
    title: 'Dining Table',
    description: 'RC Willey seats 6',
    price: '$500',
    main_image: 'https://i.imgur.com/xSfuhAF.jpg',
    second_image: 'https://i.imgur.com/PzStUrR.jpg',
    third_image: '',
    zipcode: '84108',
    user_id: '10',
      },
  {
    title: 'Fridge Samsung',
    description: 'Like new only 2 years old',
    price: '500',
    main_image: 'https://i.imgur.com/uI2eYpn.jpg',
    second_image: '',
    third_image: '',
    zipcode: '84108',
    user_id: '21',
    
  },
  {
    title: 'Mountain Bike',
    description: '2015 Cannondale XT',
    price: '1200',
    main_image: 'https://i.imgur.com/WT9gr5R.jpg',
    second_image: '',
    third_image: '',
    zipcode: '84120',
    user_id: '15',
    
  },
  {
    title: 'Bissel Carpet Cleaner',
    description: 'Carpet Steamer with cleaning solution',
    price: '100',
    main_image: 'https://i.imgur.com/54g3Bj0.jpg',
    second_image: '',
    third_image: '',
    zipcode: '84020',
    user_id: '8',
    
    
  },
  {
    title: 'Sony Soundbar',
    description: 'Sony Atmos Soundbar',
    price: '400',
    main_image: 'https://i.imgur.com/yM3rXeJ.jpg',
    second_image: '',
    third_image: '',
    zipcode: '84108',
    user_id: '1',
    
  },
  {
    title: 'Samsung Galaxy 22',
    description: 'Unlocked Android Galaxy 22 Samsung Phone',
    price: '800',
    main_image: 'https://i.imgur.com/cK5YJsX.jpg',
    second_image: '',
    third_image: '',
    zipcode: '84120',
    user_id: '19',
    
  },
  {
    title: 'Kitchen Aid Mixer',
    description: 'Kitchen Aid Mixer',
    price: '250',
    main_image: 'https://i.imgur.com/K6Cxnny.jpg',
    second_image: '',
    third_image: '',
    zipcode: '84020',
    user_id: '17',
      },
  {
    title: '2020 Toyota Camry',
    description: '36k miles Toyota 4 cylinder SE',
    price: '20000',
    main_image: 'https://i.imgur.com/ca9bcXZ.jpg',
    second_image: 'https://i.imgur.com/Hg4FOUy.jpg',
    third_image: '',
    zipcode: '84120',
    user_id: '9',
    
  },
  {
    title: 'Christmas Tree',
    description: '6ft Artificial Xmas Tree',
    price: '100',
    main_image: 'https://i.imgur.com/dbhjT59.jpg',
    second_image: '',
    third_image: '',
    zipcode: '84108',
    user_id: '10',
    
  },
  {
    title: 'Oral B Electric Toothbrush New',
    description: 'Toothbrush new in box',
    price: '90',
    main_image: 'https://i.imgur.com/atD3UN5.jpg',
    second_image: '',
    third_image: '',
    zipcode: '84108',
    user_id: '13',
    
  },
  {
    title: 'Minky Couture Blanket',
    description: 'Belgian Waffle Oatmeal - Grande',
    price: '200',
    main_image: 'https://i.imgur.com/t5ap0hR.jpg',
    second_image: '',
    third_image: '',
    zipcode: '84120',
    user_id: '21',
      },
  {
    title: 'Large Dog Kennel',
    description: 'Dog kennel for large dogs',
    price: '20',
    main_image: 'https://i.imgur.com/d5iYcVX.jpg',
    second_image: '',
    third_image: '',
    zipcode: '84020',
    user_id: '20',
   
  },
  {
    title: 'Canon EOS Rebel',
    description: 'Rebel T7 DSLR camera',
    price: '4799',  
    main_image: 'https://i.imgur.com/BKHrhoT.jpg',
    second_image: '',
    third_image: '',
    zipcode: '84108',
    user_id: '19',
  },
  {
    title: 'Tesla Model 3',
    description: 'Dual motor AWD and Performance, Only 23k miles',
    price: '39999',
    main_image: 'https://i.imgur.com/ooyNMDU.jpg',
    second_image: 'https://i.imgur.com/oL962I9.jpg',
    third_image: '',
    zipcode: '84120',
    user_id: '18',
    
  },
  {
    title: 'Sectional Sofa',
    description: 'Daydreamer Modular Four-Piece Sectional',
    price: '3999',
    main_image: 'https://i.imgur.com/L9sjwio.jpg',
    second_image: '',
    third_image: '',
    zipcode: '84020',
    user_id: '17',
  
  },
  {
    title: 'Air Jordans',
    description: 'Nike Air Jordans',
    price: '600',
    main_image: 'https://i.imgur.com/45dILi0.jpg',
    second_image: 'https://i.imgur.com/QpQclFO.jpg',
    third_image: '',
    zipcode: '84120',
    user_id: '16',
    
  },
  {
    title: '55 Inch TV',
    description: 'Sony LED Smart TV',
    price: '800',
    main_image: 'https://i.imgur.com/IcCki20.jpg',
    second_image: 'https://i.imgur.com/HEfZyBA.jpg',
    third_image: '',
    zipcode: '84108',
    user_id: '15',
    
  },
  {
    title: '65 Inch TV',
    description: 'LG Oled TV',
    price: '1300',
    main_image: 'https://i.imgur.com/1pajrrj.jpg',
    second_image: '',
    third_image: '',
    zipcode: '84108',
    user_id: '14',
  },
  {
    title: 'Mountain Bike',
    description: 'Specialized Stumpjumper S-Works',
    price: '5550',
    main_image: 'https://i.imgur.com/eZ8mT7d.jpg',
    second_image: 'https://i.imgur.com/cyRz8ee.jpg',
    third_image: '',
    zipcode: '84120',
    user_id: '11',
  },
  {
    title: 'Pivot Shuttle SL eBike',
    description: 'Pivot SL light weight ebike',
    price: '12150',
    main_image: 'https://i.imgur.com/49M4t5j.jpg',
    second_image: '',
    third_image: '',
    zipcode: '84120',
    user_id: '12',
  },
];

const seedProducts = () => Products.bulkCreate(productdata);

module.exports = seedProducts;
